### ISSUE TITLE
Purchases are failing on micromasters-rc due to enrollment failure

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1550] opened 2016-10-25 19:29 UTC
Found this when trying to check off my boxes for the release. Here's the response when the enrollment:

```
{
    "enrollment_detail": {
        "course_details": {
            "course_end": null,
            "course_id": "ccx-v1:MITx+Giovanni101+2015_T3+ccx@38",
            "course_modes": [
                {
                    "bulk_sku": null,
                    "currency": "usd",
                    "description": null,
                    "expiration_datetime": null,
                    "min_price": 0,
                    "name": "Audit",
                    "sku": null,
                    "slug": "audit",
                    "suggested_prices": ""
                }
            ],
            "course_start": "2016-03-04T12:02:25Z",
            "enrollment_end": null,
            "enrollment_start": "2016-01-01T00:00:00Z",
            "invite_only": false
        },
        "created": "2016-04-04T14:22:48Z",
        "is_active": true,
        "mode": "audit",
        "user": "gschneel"
    },
    "message": "An enrollment already exists for user [gschneel] in course run [ccx-v1:MITx+Giovanni101+2015_T3+ccx@38]."
}
```

On my local machine:

```
{
    "course_details": {
        "course_end": null,
        "course_id": "course-v1:MIT+GEO102+GEO_T1",
        "course_modes": [
            {
                "bulk_sku": null,
                "currency": "usd",
                "description": null,
                "expiration_datetime": null,
                "min_price": 0,
                "name": "Audit",
                "sku": null,
                "slug": "audit",
                "suggested_prices": ""
            }
        ],
        "course_start": "2030-01-01T00:00:00Z",
        "enrollment_end": null,
        "enrollment_start": null,
        "invite_only": false
    },
    "created": "2016-06-30T21:50:20.225984Z",
    "is_active": true,
    "mode": "audit",
    "user": "staff"
}
```

**Comment by pdpinch** [comment] 2016-10-26 16:10
This is an upstream issue at edX that was caused by a change to the enrollment API. The commit at https://github.com/edx/edx-platform/commit/21746f1e93f24244d7dad799aef5c7265cf59e65 changed the response from the enrollment API and broke our edx-api client. 

In the current code, users will not be able to "enroll and pay later" and if they do pay, they can complete the transaction, but the portal will not recognize it. Possible errors include a [DoesNotExist execption](https://sentry.io/mit-office-of-digital-learning/micromasters/issues/174176463/)

According to [JIRA ECOM-6213](https://openedx.atlassian.net/browse/ECOM-6213), edX plans to revert this change. (They may also release an updated version of the API with a new version number).

**Comment by pdpinch** [comment] 2016-10-28 13:08
edX has merged the revert to this API change: https://github.com/edx/edx-platform/pull/13849

**Comment by pdpinch** [comment] 2016-10-28 18:40
edX released this fix to their staging stack today, so micromasters-rc should be functional again. 

The fix will be released to production on or about Wednesday 11/2.

**Comment by pdpinch** [comment] 2016-11-03 13:57
confirmed fixed on 11/2

**Closed by pdpinch** 2016-11-03 13:57 UTC
Labels: bug, Release blocker
