### ISSUE TITLE
oauth authentication fails with HTTPError: 401 Client Error: 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2101] opened 2016-12-13 16:29 UTC
Giovanni, can you take a quick look at this? I can't tell what's happening here, and whether it's a user-facing issue. It does occur in production. 

https://sentry.io/mit-office-of-digital-learning/micromasters/issues/182642956/

```
HTTPError: 401 Client Error: UNAUTHORIZED for url: https://courses.edx.org/oauth2/access_token/
(12 additional frame(s) were not displayed)
...
  File "social/backends/oauth.py", line 393, in auth_complete
    method=self.ACCESS_TOKEN_METHOD
  File "social/backends/oauth.py", line 371, in request_access_token
    return self.get_json(*args, **kwargs)
  File "social/backends/base.py", line 229, in get_json
    return self.request(url, *args, **kwargs).json()
  File "social/backends/base.py", line 225, in request
    response.raise_for_status()
  File "requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

HTTPError: 401 Client Error: UNAUTHORIZED for url: https://courses.edx.org/oauth2/access_token/
```

**Comment by giocalitri** [comment] 2017-01-03 20:40
is this a duplicate of #2132 ? Can we close it?

**Comment by pdpinch** [comment] 2017-01-03 20:56
Same error, different API endpoint. If you think there's one solution that fixes both, then feel free to close one of them.

**Comment by giocalitri** [comment] 2017-01-03 20:57
Yes, I think the problem/solution is the same

**Closed by giocalitri** 2017-01-03 20:57 UTC
