### ISSUE TITLE
facets box goes on top of footer

### ISSUE THREAD

**Issue by giocalitri** [mitodl/micromasters#1948] opened 2016-12-02 19:32 UTC
![screen shot 2016-12-02 at 2 31 27 pm](https://cloud.githubusercontent.com/assets/1005204/20847445/18f83fea-b89c-11e6-8dbe-3b17fb5cb0c2.png)

**Comment by singingwolfboy** [comment] 2016-12-08 16:33
We're using [React-Sticky](https://github.com/captivationsoftware/react-sticky) on the facets sidebar, which causes the sidebar to have `position: fixed` styling. This prevents the rest of the page from being able to reflow around it, which is why the footer is colliding with the sidebar when the page is scrolled down far enough. React-Sticky seems to be designed with full-width elements in mind, like a sticky menu bar (see [example 1](http://rawgit.com/captivationsoftware/react-sticky/master/examples/basic/index.html) and [example 2](http://rawgit.com/captivationsoftware/react-sticky/master/examples/timeline/index.html)), so it may not account for this case. I'm going to keep digging.

**Comment by singingwolfboy** [comment] 2016-12-08 18:19
After some additional testing, I can confirm that React-Sticky completely ignores this use-case. In React-Sticky's view, there are only two states for an element: sticky or not. If it's sticky, it's displayed using `position: fixed`, so that it will overlap anything else on the page. If not, it's displayed using `position: static` (the default).

We need at least three states:
1. Pre-sticky, where the element is positioned at the top of its container and scrolls with the page. We can use `position: static` or `position: absolute` for this.
2. Sticky, where the element is stuck in place while the page is being scrolled through the container. We can use `position: fixed` for this.
3. Post-sticky, where the element is positioned at the bottom of its container and scrolls with the page. We can use `position: absolute` and `bottom: 0` for this.

The only other module I've found that might be relevant here is [`react-stickynode`](https://github.com/yahoo/react-stickynode), which claims to support more features than `react-sticky`, including sticking to the bottom of an element instead of the top. However, when I tried using `react-stickynode` for this case, the behavior was completely incorrect: the element was sticky when I scrolled down, but moved with the page when I scrolled up. As a result, the element quickly found its way to the bottom of the page, and never came back up again. Perhaps I misconfigured something?

At any rate, it looks like fixing this will be a lot of work. There is already [a pull request for `react-sticky` to allow it to stick to the bottom of an element](https://github.com/captivationsoftware/react-sticky/pull/132), but it hasn't been merged, so we'll need to test it and fix whatever bugs we find. We'll also need to add the "post-sticky" state, and test that.

@pdpinch, is this worth the effort?

**Comment by pdpinch** [comment] 2016-12-08 19:18
@roberthouse54 it's looking like making the facets "sticky" has had some unintended consequences that we can't easily work around. Is it really necessary? Can we just let them scroll with everything else?

We made them sticky in response to request you made back at https://github.com/mitodl/micromasters/issues/934#issuecomment-245000045

**Comment by roberthouse54** [comment] 2016-12-08 19:56
OK, let's kill the stickiness.

**Closed** 2016-12-12 16:04 UTC
Labels: bug, UX
