### ISSUE TITLE
Course status does not change after "enroll and pay later"

### ISSUE THREAD

**Issue by Ferdi** [mitodl/micromasters#1444] opened 2016-10-18 20:20 UTC
Steps to reproduce
- Click "Enroll and Pay later"
- Seems like nothing happens in dashboard

However I was successfully enrolled in the course. 

Chrome says : 

![s](https://cloud.githubusercontent.com/assets/125561/19494746/89d95698-954e-11e6-85b8-e90fc31e0a1a.png)

**Comment by pdpinch** [comment] 2016-10-19 19:59
@noisecapella and @aliceriot do you think this uncaught error is related to the issue that Ferdi had?

@blarghmatey how can we make sure Sentry catches these errors?

**Comment by noisecapella** [comment] 2016-10-19 20:03
That error looks like a validation error that happened when completing the profile, I'm not sure it's related. @Ferdi what instance did you hit this error on? Is it easily reproducable?

**Comment by pdpinch** [comment] 2016-10-24 18:11
trying this again, I'm seeing a 500 error for the course "supply chain dynamics" on micromasters-ci.

**Comment by Ferdi** [comment] 2016-10-24 19:23
@blarghmatey I'm sure it was production

**Comment by pdpinch** [comment] 2016-11-18 13:49
@j2tausig have you been able to reproduce this?

**Comment by j2tausig** [comment] 2016-11-18 14:21
Tried this on RC -- Supply Chain Analytics.  When I click on "Enroll and Pay Later" -- nothing happens.

**Comment by pdpinch** [comment] 2016-11-18 16:30
Just to confirm -- nothing happens, or you are enrolled, but the dashboard doesn't respond?

**Comment by j2tausig** [comment] 2016-11-18 17:21
Nothing happens.  I do not believe I'm enrolled based on this:
{
  "course_title": "Supply Chain Analytics",
  "course_runs": [
    {
      "enrollment_end": "12/07/2016",
      "end_date": "12/27/2016",
      "enrollment_start": "04/30/2016",
      "edx_course_key": "course-v1:MITx+CTL.SC0x+3T2016",
      "start_date": "11/01/2016",
      "upgrade_deadline": "12/07/2016",
      "id": 1
    }
  ]

**Comment by pdpinch** [comment] 2016-11-18 17:52
@j2tausig Which course were you attempting to enroll in?

I think this was a misconfiguration (no course on stage stack) which I've corrected. 

Even it works though, I think we need better error messaging / handling here.

**Comment by j2tausig** [comment] 2016-11-18 17:59
"course_title": "Supply Chain Analytics",

**Comment by pdpinch** [comment] 2016-11-18 18:47
I'm going to close this because it was caused by configuration issues in testing.

I've opened two other issues about improving the error handling, #1815 (notify the user) and #1817 (notify us)

**Closed by pdpinch** 2016-11-18 18:47 UTC
