### ISSUE TITLE
Course grade histogram overlaps site footer with short window

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#1987] opened 2016-12-06 01:37 UTC
<img width="779" alt="ss 2016-12-05 at 20 22 48" src="https://cloud.githubusercontent.com/assets/14932219/20909580/9590fcb4-bb2a-11e6-93a2-67181f8a0602.png">

**Comment by pdpinch** [comment] 2016-12-06 12:08
duplicate of #1948

**Comment by singingwolfboy** [comment] 2016-12-08 20:31
#2046 fixes this issue.

**Closed** 2016-12-13 16:43 UTC
Labels: bug, duplicate
