### ISSUE TITLE
(Bug) Tabbing to text input field causes weird input behavior

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#716] opened 2016-07-13 18:02 UTC
**To reproduce:**

1. Open the personal tab of the profile edit form with a non-blank last name (users page or profile, doesn't matter)
1. Click on the first name field to focus on it
1. Hit tab to navigate to the last name field and highlight the text
1. Hit the left arrow key to deselect the text and move the cursor to the beginning of the input
1. Type two letters

**Expected:** The two letters would be inserted at the position of the text cursor (ie: the beginning of the input
**Actual:** The first letter is inserted at the beginning of the input, and the second letter is inserted at the end

**Comment by aliceriot** [comment] 2016-07-14 14:19
this is a duplicate of https://github.com/mitodl/micromasters/issues/665 I think, although before we didn't realize that it applied to already filled fields. Regardless, it seems to be an upstream issue.

**Closed** 2016-07-14 15:33 UTC
Labels: bug

**Comment by gsidebo** [comment] 2016-07-14 15:35
is indeed a duplicate
