### ISSUE TITLE
Navigation between first and second tab in the Profile Flow

### ISSUE THREAD

**Issue by j2tausig** [mitodl/micromasters#1360] opened 2016-10-12 21:12 UTC
##The issue is that when navigating from the first to second tab in Profile Flow, the user selects the "Next" button at the bottom of the first tab in the flow.  But when the second tab renders they are still at the bottom of the page -- they should be at the top when rendering is complete.

Steps to Reproduce:
micromasters.herokuapp.com
Create a new user.
Fill out the entire form on the first profile page (https://micromasters.herokuapp.com/profile/)
At the bottom of the page, click on the "next" button to submit.
Note: the second tab renders without scrolling the user to the top.

![bottom of page](https://cloud.githubusercontent.com/assets/13886722/19327798/c1f6aa1c-909e-11e6-9679-476701c0b5b1.PNG)
![scroll to top](https://cloud.githubusercontent.com/assets/13886722/19327805/c9ca0694-909e-11e6-9865-c0f7867fc14c.PNG)

This was an issue in both Edge and Safari (was not tested in either Firefox or Chrome).

**Comment by pdpinch** [comment] 2016-11-04 13:13
duplicate of #756

**Comment by pdpinch** [comment] 2016-11-29 13:55
Closed by #1616

**Closed by pdpinch** 2016-11-29 13:55 UTC
Labels: duplicate, enhancement
