### ISSUE TITLE
Dashboard: Allow enrolling a future course run

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#833] opened 2016-08-11 19:44 UTC
- [ ] Add information to the dashboard API to allow re-enrolling in a future course run (the course key and course start date of the next course run)
- [ ] Implement design for a user who has failed and has the option to enroll in a future course run (see mockup in #925)

**Comment by noisecapella** [comment] 2016-08-19 20:00
We should also change the status from `enrolled-not-verified` to just `enrolled`, and all the other statuses in the same way, since the status shouldn't indicate the direction to the next status (for example `offered-not-enrolled` will actually show a button which verifies the user.)

**Comment by noisecapella** [comment] 2016-09-13 21:53
I updated the description with a list of specific items. I'm not sure how the API would need to change for handling failed courses, feel free to weigh in @giocalitri since we talked about this a long time ago.

**Comment by gsidebo** [comment] 2016-09-14 02:58
there are a few statuses that we really should change

**Comment by noisecapella** [comment] 2016-09-14 14:58
@gsidebo What status name changes would you suggest?

**Comment by gsidebo** [comment] 2016-09-15 18:25
right now i can't say for sure exactly - i wasn't around when the reasoning behind these statuses was discussed, and figuring out the causes and purposes of these statuses from the code is very difficult. i'll start by listing some problematic names

```python
class CourseStatus:
    PASSED = 'passed'
    NOT_PASSED = 'not-passed'
    CURRENT_GRADE = 'verified'
    UPGRADE = 'enrolled'
    OFFERED = 'offered'

class CourseRunStatus:
    NOT_ENROLLED = 'not-enrolled'
    GRADE = 'grade'
    READ_CERT = 'read-cert'
    WILL_ATTEND = 'will-attend'
    UPGRADE = 'upgrade'
    NOT_PASSED = 'not-passed'
```

the following just don't make sense semantically (to me, anyway):

- `CourseStatus.CURRENT_GRADE`
- `CourseStatus.UPGRADE`
- `CourseRunStatus.GRADE`
- `CourseRunStatus.UPGRADE`
- `CourseRunStatus.READ_CERT`

when i see that some course run has been given the status of `CourseStatus.PASSED`, that makes semantic sense, and it tells me something meaningful about the course. when i see that a course run has been given the status of, say, `CourseStatus.CURRENT_GRADE`, that makes no semantic sense. it adds to the cognitive load of reading and reasoning about the code. i think it would help to change these variables (and their values) to adjective-like descriptors of a user's course run.

there is also disagreement between the class property names and the values they represent (eg: `CURRENT_GRADE = 'verified'`, `UPGRADE = 'enrolled'`). also confusing, and it doesn't seem necessary.

aside: i also think the class names `CourseStatus` and `CourseRunStatus` are tremendously confusing. i see that the docstring indicates that `CourseRunStatus` is only used internally, but both of them seem to be used to represent statuses for a course run for a user. the apparent overlap between them (`NOT_PASSED`, `UPGRADE`) makes it more confusing. i'm not entirely sure about alternatives, but perhaps `DisplayedCourseRunStatus` and `UserCourseRunStatus` would be more helpful?

**Comment by noisecapella** [comment] 2016-09-16 14:42
I agree about the confusion, feel free to make a PR to change the status names if you prefer

**Comment by pdpinch** [comment] 2016-10-06 21:05
@gsidebo do you think this is done now that #1061 is merged?

**Comment by gsidebo** [comment] 2016-10-11 14:24
Closing as duplicate of #939

**Closed by gsidebo** 2016-10-11 14:24 UTC
Labels: October 15
