### ISSUE TITLE
page_404 error

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1248] opened 2016-10-05 19:15 UTC
I ran into this when I was directed back to the dashboard after fulfilling the order

    2016-10-05T19:11:21.107661+00:00 app[web.1]: [2016-10-05 19:11:21] WARNING 18 [django.request] base.py:182 - [b88fcf9b-672f-4997-9725-26581357feca] - Not Found: /favicon.ico
    2016-10-05T19:11:21.128502+00:00 app[web.1]: [2016-10-05 19:11:21] DEBUG 18 [django.template] base.py:927 - [b88fcf9b-672f-4997-9725-26581357feca] - Exception while resolving variable 'style_public_src' in template '404.html'.
    2016-10-05T19:11:21.128504+00:00 app[web.1]: Traceback (most recent call last):
    2016-10-05T19:11:21.128505+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/django/core/handlers/base.py", line 134, in get_response
    2016-10-05T19:11:21.128506+00:00 app[web.1]:     resolver_match = resolver.resolve(request.path_info)
    2016-10-05T19:11:21.128507+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/newrelic-2.54.0.41/newrelic/hooks/framework_django.py", line 553, in wrapper
    2016-10-05T19:11:21.128507+00:00 app[web.1]:     return _wrapped(*args, **kwargs)
    2016-10-05T19:11:21.128508+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/newrelic-2.54.0.41/newrelic/hooks/framework_django.py", line 541, in _wrapped
    2016-10-05T19:11:21.128509+00:00 app[web.1]:     result = wrapped(path)
    2016-10-05T19:11:21.128509+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/django/core/urlresolvers.py", line 404, in resolve
    2016-10-05T19:11:21.128510+00:00 app[web.1]:     raise Resolver404({'tried': tried, 'path': new_path})
    2016-10-05T19:11:21.128525+00:00 app[web.1]: django.core.urlresolvers.Resolver404: {'path': 'favicon.ico', 'tried': [[<RegexURLResolver <module 'ui.urls' from './ui/urls.py'> (None:None) >, <RegexURLPattern None ^logout/$>], [<RegexURLResolver <module 'ui.urls' from './ui/urls.py'> (None:None) >, <RegexURLPattern ui-404 ^404/$>], [<RegexURLResolver <module 'ui.urls' from './ui/urls.py'> (None:None) >, <RegexURLPattern ui-500 ^500/$>], [<RegexURLResolver <module 'ui.urls' from './ui/urls.py'> (None:None) >, <RegexURLPattern ui-users ^users/(?P<user>[-\w]+)?/?>], [<RegexURLResolver <module 'ui.urls' from './ui/urls.py'> (None:None) >, <RegexURLPattern terms_of_service ^terms_of_service/$>], [<RegexURLResolver <module 'ui.urls' from './ui/urls.py'> (None:None) >, <RegexURLPattern ui-dashboard ^dashboard/$>], [<RegexURLResolver <module 'ui.urls' from './ui/urls.py'> (None:None) >, <RegexURLPattern ui-dashboard ^profile/$>], [<RegexURLResolver <module 'ui.urls' from './ui/urls.py'> (None:None) >, <RegexURLPattern ui-dashboard ^settings/$>], [<RegexURLResolver <module 'ui.urls' from './ui/urls.py'> (None:None) >, <RegexURLPattern ui-dashboard ^learners/$>], [<RegexURLResolver <module 'social.apps.django_app.urls' from '/app/.heroku/python/lib/python3.5/site-packages/social/apps/django_app/urls.py'> (None:social) >, <RegexURLPattern begin ^login/(?P<backend>[^/]+)/$>], [<RegexURLResolver <module 'social.apps.django_app.urls' from '/app/.heroku/python/lib/python3.5/site-packages/social/apps/django_app/urls.py'> (None:social) >, <RegexURLPattern complete ^complete/(?P<backend>[^/]+)/$>], [<RegexURLResolver <module 'social.apps.django_app.urls' from '/app/.heroku/python/lib/python3.5/site-packages/social/apps/django_app/urls.py'> (None:social) >, <RegexURLPattern disconnect ^disconnect/(?P<backend>[^/]+)/$>], [<RegexURLResolver <module 'social.apps.django_app.urls' from '/app/.heroku/python/lib/python3.5/site-packages/social/apps/django_app/urls.py'> (None:social) >, <RegexURLPattern disconnect_individual ^disconnect/(?P<backend>[^/]+)/(?P<association_id>[^/]+)/$>], [<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <RegexURLPattern list> (None:None) ^api/v0/>], [<RegexURLPattern dashboard_api ^api/v0/dashboard/$>], [<RegexURLPattern search_api ^api/v0/search/(?P<elastic_url>.*)>], [<RegexURLPattern checkout ^api/v0/checkout/$>], [<RegexURLPattern user_program_enrollments ^api/v0/enrolledprograms/$>], [<RegexURLPattern search_result_mail_api ^api/v0/mail/$>], [<RegexURLPattern financial_aid_mail_api ^api/v0/financial_aid_mail/(?P<financial_aid_id>[\d]+)/$>], [<RegexURLPattern financial_aid_request ^api/v0/financial_aid_request/$>], [<RegexURLPattern financial_aid_action ^api/v0/financial_aid_action/(?P<financial_aid_id>[\d]+)/$>], [<RegexURLPattern financial_aid_skip ^api/v0/financial_aid_skip/(?P<program_id>[\d]+)/$>], [<RegexURLPattern financial_aid ^api/v0/financial_aid/(?P<financial_aid_id>[\d]+)/$>], [<RegexURLPattern course_price_list ^api/v0/course_prices/$>], [<RegexURLPattern course_price_detail ^api/v0/course_prices/(?P<program_id>[\d]+)/$>], [<RegexURLPattern order-fulfillment ^api/v0/order_fulfillment/$>], [<RegexURLResolver <module 'server_status.urls' from '/app/.heroku/python/lib/python3.5/site-packages/server_status/urls.py'> (None:None) ^status/>], [<RegexURLResolver <module 'financialaid.urls' from './financialaid/urls.py'> (None:None) ^financial_aid/>], [<RegexURLResolver <module 'wagtail.wagtailadmin.urls' from '/app/.heroku/python/lib/python3.5/site-packages/wagtail/wagtailadmin/urls/__init__.py'> (None:None) ^cms/>], [<RegexURLResolver <module 'wagtail.wagtaildocs.urls' from '/app/.heroku/python/lib/python3.5/site-packages/wagtail/wagtaildocs/urls.py'> (None:None) ^documents/>], [<RegexURLResolver <module 'wagtail.wagtailcore.urls' from '/app/.heroku/python/lib/python3.5/site-packages/wagtail/wagtailcore/urls.py'> (None:None) >, <RegexURLPattern wagtailcore_authenticate_with_password ^_util/authenticate_with_password/(\d+)/(\d+)/$>], [<RegexURLResolver <module 'wagtail.wagtailcore.urls' from '/app/.heroku/python/lib/python3.5/site-packages/wagtail/wagtailcore/urls.py'> (None:None) >, <RegexURLPattern wagtail_serve ^((?:[\w\-]+/)*)$>]]}
    2016-10-05T19:11:21.128526+00:00 app[web.1]: 
    2016-10-05T19:11:21.128526+00:00 app[web.1]: During handling of the above exception, another exception occurred:
    2016-10-05T19:11:21.128527+00:00 app[web.1]: 
    2016-10-05T19:11:21.128527+00:00 app[web.1]: Traceback (most recent call last):
    2016-10-05T19:11:21.128528+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/django/core/handlers/base.py", line 92, in get_exception_response
    2016-10-05T19:11:21.128528+00:00 app[web.1]:     response = callback(request, **dict(param_dict, exception=exception))
    2016-10-05T19:11:21.128529+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/newrelic-2.54.0.41/newrelic/hooks/framework_django.py", line 499, in wrapper
    2016-10-05T19:11:21.128529+00:00 app[web.1]:     return wrapped(*args, **kwargs)
    2016-10-05T19:11:21.128530+00:00 app[web.1]: TypeError: page_404() got an unexpected keyword argument 'exception'
    2016-10-05T19:11:21.128530+00:00 app[web.1]: 
    2016-10-05T19:11:21.128531+00:00 app[web.1]: During handling of the above exception, another exception occurred:
    

![screenshot from 2016-10-05 15-14-37](https://cloud.githubusercontent.com/assets/863262/19127775/79ff058c-8b0e-11e6-8c55-b92b1568d570.png)

After a refresh everything worked fine

**Comment by noisecapella** [comment] 2016-10-05 19:17
I'm not sure if this is a newrelic error or an error on our side. I'm also confused about the 404 part. At least we should change `page_404` to accept args and kwargs so this error isn't possible

**Comment by pdpinch** [comment] 2016-10-06 16:43
@alvinsiu can you take a look into this?

**Comment by noisecapella** [comment] 2016-10-06 17:23
FYI this was a momentary error I got on micromasters-rc so it will be difficult to reproduce

**Comment by alvinsiu** [comment] 2016-10-06 19:27
Looking into this now

**Comment by alvinsiu** [comment] 2016-10-06 21:41
Hmmmm, without any way to reproduce this error or to get more of the traceback, I'm not sure we'll be able to figure out anything about what happened.

The `Exception while resolving variable 'style_public_src' in template '404.html'.` is not relevant.  [Django 1.10 will print to console if there are missing context variables.](https://docs.djangoproject.com/en/1.10/topics/logging/#django-template)  Though it is curious that `404.html` inherits from `base_error.html`, neither of which reference `style_public_src`.

@noisecapella Would you happen to have more of the stacktrace saved?  I don't think I can access the heroku logs from 10/5.  in `django.core.handlers.base.BaseHandler.get_exception_response`, it handles the case where error handlers should accept an exception parameter (where here newrelic did not).  I would guess there may be more clues there about what went wrong here.

**Comment by noisecapella** [comment] 2016-10-06 21:42
Yes actually, I'll send it over hipchat

**Comment by alvinsiu** [comment] 2016-10-06 21:43
Thanks!

**Comment by noisecapella** [comment] 2016-10-06 22:18
I think even if you're unable to find any definitive cause we should still add a `*args, **kwargs` to the 404 and 500 views as a precaution

**Comment by alvinsiu** [comment] 2016-10-06 22:43
The issue was `signed_field_names` was not passed with `request.data` in `ecommerce.permissions.IsSignedByCyberSource`, so `ecommerce.api.generate_cybersource_sa_signature` errored out with a `MultiValueDictKeyError` when trying to make a request to `ecommerce.views.OrderFulfillmentView`.

I made a [pull request](https://github.com/mitodl/micromasters/pull/1277) to fix that from erroring out, but I'm probably not familiar enough with ecommerce to assess/fix if anything else needs to be done in terms of why that's the case.

**Comment by noisecapella** [comment] 2016-10-07 14:30
I think you're looking at a different stack trace. `/api/v0/order_fulfillment/` is accessed at the same time as the user is redirected back to the dashboard, but they're technically two separate requests. Only Cybersource will access `/api/v0/order_fulfillment/`, the user will never touch that endpoint. The error occurred when the user downloaded from `/dashboard/`

**Comment by alvinsiu** [comment] 2016-10-07 14:35
Hmmm - is the PR #1277 for the `MultiValueDictKeyError`s still relevant in terms of Cybersource trying to access `/api/v0/order_fulfillment/` then?  It also implements adding `*args, **kwargs` to `page_404`. If not, I can close that PR.

**Comment by alvinsiu** [comment] 2016-10-10 16:36
@noisecapella Should we leave this issue open or close it?  #1277 doesn't fix the root cause of this bug, but not sure if this bug is defined enough to be diagnosed without more info.

**Closed** 2016-10-11 15:32 UTC
Labels: bug
