### ISSUE TITLE
set-value upgrade

### ISSUE THREAD

**Issue by Ferdi** [mitodl/micromasters#4518] opened 2020-02-03 22:47 UTC
┆Issue is synchronized with this [Trello card](https://trello.com/c/aepEhICi) by [Unito](https://www.unito.io/learn-more)

**Comment by Ferdi** [comment] 2020-02-04 18:44
➤ Anna Gavrilman commented:

this is fixed by the webpack upgrade

**Comment by annagav** [comment] 2020-02-04 18:54
this is a duplicate of #4505

**Closed by annagav** 2020-02-04 18:54 UTC
