### ISSUE TITLE
Long delay in loading programs in profile form

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1655] opened 2016-11-04 12:34 UTC
Steps to reproduce:

1. On an account without a profile, load the profile form

## Expected Behavior

When the form loads and becomes interactive, the programs select list has two (or more) options. 

## Actual Behavior

When the form loads and the programs select is interactive, there are no options available. 

It takes a few more seconds after the form loads for the programs drop down to be populated. Since it's the first field in the form, users are confused why there are no choices from the drop-down.

**Comment by pdpinch** [comment] 2016-11-07 18:15
Related issue from @singingwolfboy about what happens when the API fails. We could add a handler in the UI, directing the user to contact support.

**Comment by giocalitri** [comment] 2016-11-07 20:22
I have seen this problem in the past but I am unable to reproduce it now on local environment and on staging.
In general what do we want the approach to solve the problem to be? 
Do we want to load the JSON in the html template?

**Comment by noisecapella** [comment] 2016-11-07 20:27
After #1569 was merged we started using `/api/v0/programs/` instead of `/api/v0/dashboard/` for the program information in the profile form, so that may explain why the problem doesn't appear anymore

**Comment by giocalitri** [comment] 2016-11-08 18:25
so is this still an issue

**Comment by rhysyngsun** [comment] 2016-11-08 21:35
Locally for me at least this select populates immediately for me as well.

**Comment by pdpinch** [comment] 2016-11-09 16:18
It seems to me that we're making 4 API calls to load the profile page, when only 2 should be enough. Given the blocking nature of dashboard, I think it may have been the root cause of this UX problem I was seeing. Can we remove it from the profile view?

I have no idea why we call course_price here either.

**Comment by noisecapella** [comment] 2016-11-09 16:20
Yes, we should be able to delay those API calls until the user sees the actual dashboard

**Comment by noisecapella** [comment] 2016-11-14 15:16
> Related issue from @singingwolfboy about what happens when the API fails. We could add a handler in the UI, directing the user to contact support. 
Is this part of this issue?

**Closed** 2016-11-16 20:26 UTC
Labels: Release blocker
