### ISSUE TITLE
enterring an address longer than 100 characters results in a 400 error

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4618] opened 2020-06-15 22:36 UTC
### Steps to Reproduce

1. Go to /profile/personal
2. Fill out the form and enter an address over 100 characters

### Expected Behavior

- the user should get an error message that directs them to enter a shorter address

### Actual Behavior

- user gets a 400 error, displayed on /profile/education

### API response

```{"address":["Ensure this field has no more than 100 characters."]}```

**Comment by HamzaIbnFarooq** [comment] 2020-11-16 07:47
@pdpinch This issue is a duplicate of https://github.com/mitodl/micromasters/issues/4649 and has already been resolved.

**Closed** 2020-11-16 17:21 UTC
