### ISSUE TITLE
handle 404 errors in react routing

### ISSUE THREAD

**Issue by giocalitri** [mitodl/micromasters#602] opened 2016-06-20 20:44 UTC
depends on #440 

@noisecapella was saying that react should force a reload when a route is not found to have the server  return the 404 via template.

**Comment by aliceriot** [comment] 2016-06-22 16:04
is this a duplicate of #481?

**Comment by noisecapella** [comment] 2016-06-22 16:24
Yes, looks like it

**Comment by noisecapella** [comment] 2016-06-23 18:45
Closing as duplicate of #481

**Closed by noisecapella** 2016-06-23 18:45 UTC
