### ISSUE TITLE
Fix histogram and range facets in UI

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#3095] opened 2017-04-20 18:13 UTC
We have a few UI issues with the histogram and range facets on the learner's search page

**1) When a range is selected on a histogram that yields no results, and a course filter is applied, the selected course filter remains in the facet** 

![ss 2017-04-20 at 14 04 59](https://cloud.githubusercontent.com/assets/14932219/25245497/9964ab52-25d2-11e7-8f34-5f4fb50dc6f6.png)

~~**2) The '# of courses passed' selected filter title is missing**~~

![ss 2017-04-20 at 14 05 46](https://cloud.githubusercontent.com/assets/14932219/25245508/a08cc090-25d2-11e7-81b4-1b963ea402c7.png)

**3) When a range is applied for '# of courses passed', and any course filter is also applied, the '# of courses passed' facet disappears while the filter remains**

![ss 2017-04-20 at 14 05 54](https://cloud.githubusercontent.com/assets/14932219/25245527/ae5b26e4-25d2-11e7-9e42-3c383cb6b3d8.png)

**Comment by pdpinch** [comment] 2017-05-02 17:18
These issues can be addressed in separate PRs, to make it easier to review.

**Comment by rhysyngsun** [comment] 2017-05-11 21:14
2) is easily fixed and I'll have a PR up shortly, I can't reproduce 3)

regarding 1), what's the fix that we want? I actually see that this problem can be more generalized as "when a user selected a search with no results, the selected filters appear without facet titles". For example, in the below screenshot, what would we do?
![selection_067](https://cloud.githubusercontent.com/assets/28598/25972217/19a3da5e-366d-11e7-8a76-174554b7806c.png)

Unselecting any filter
 could give you results (and it's not easy to know which ones unless you compute all those aggregation permutations), so I don't think hiding particular facets is the solution.

I think the thing that's off is that the facet title disappears, but the selection remains. I'd suggest we make sure we don't hide facet titles if we have a selection on that facet, does that make sense?

@pdpinch @gsidebo

**Comment by gsidebo** [comment] 2017-05-12 18:21
I'll see if (3) is still happening and clarify the steps to reproduce if it's still there

I'm definitely on board with keeping the facet titles around if there is a selection. That makes the most sense to me. If that looks especially difficult, we can discuss other options

**Comment by gsidebo** [comment] 2017-05-12 18:50
@rhysyngsun (3) is still happening on master:
<img width="1023" alt="ss 2017-05-12 at 14 47 36" src="https://cloud.githubusercontent.com/assets/14932219/26012239/e601d86c-3721-11e7-9172-06dda5ab8132.png">

The '# of courses passed' range is applied (see selected filters), but the facet is missing.

To reproduce:

1) Adjust the bounds of the '# of courses passed' range filter (I set it to 2-3)
2) Select any one of the course title filters (I chose 'Digital Learning 100')

Result: '# of courses passed' facet should still be there on the left side. It ain't

**Comment by rhysyngsun** [comment] 2017-05-12 19:42
(3) appears to be an issue with SearchKit's `RangeFilter`, specifically how `isDisabled` is defined in `RangeAccessor`, so that will require yet another custom subclass to fix. :monkey:

**Comment by rhysyngsun** [comment] 2017-05-16 20:17
Reopening because the third PR accidentally closed this.

**Closed** 2017-05-18 14:31 UTC
Labels: bug
