### ISSUE TITLE
Scroll function not working on popups with Edge & IE 11

### ISSUE THREAD

**Issue by j2tausig** [mitodl/micromasters#1424] opened 2016-10-17 19:08 UTC
On the profile page, for any of the pop-ups that are spawned (Preferred Language, Country, State) in Edge & IE11, if no value is selected, clicking on either the slider or the up/down arrow closes the window rather than navigates through the list of values.

Steps to Reproduce:
Log into MicroMasters using either Edge & IE11.
Create a Profile on edX.
On the first Profile Tab, click on one of the following fields:
Preferred Language, Country or State.
If NO value is populated in that field,  note that in the pop-up window if you click
on either the slider or the up/down arrow, the window is closed.
(if the field is populated with a value, then those navigation elements work)

Expected Behavior:
Navigation elements should allow the user to scroll up or down the list.

This IS working in Firefox & Chrome.

**Comment by aliceriot** [comment] 2016-10-20 14:55
looks like this is an upstream issue: https://github.com/callemall/material-ui/issues/5178

**Comment by aliceriot** [comment] 2016-10-20 15:12
I'm going to try bumping the material-ui version and see if that fixes anything

**Comment by aliceriot** [comment] 2016-10-20 15:13
we're currently using `0.15.0`, latest is `0.16.1`.

**Comment by aliceriot** [comment] 2016-10-20 15:20
bah I forgot we can't do that, since we had to patch autocomplete a while back.

tbh I don't think there's an easy way to fix this.

**Comment by aliceriot** [comment] 2016-10-20 15:22
@pdpinch

**Comment by noisecapella** [comment] 2016-10-20 15:22
Does 0.16.1 have the issue if we use the upstream AutoComplete?

**Comment by aliceriot** [comment] 2016-10-20 15:26
I haven't explored that yet because the modified code we checked in has dependencies and stuff that aren't pulled in anymore.

Why did we have to modify those things anyway? I don't remember.

**Comment by noisecapella** [comment] 2016-10-20 15:28
We integrated react-virtualized into AutoComplete to make performance better for long lists. I think we changed a few other things over the months but that was the main thing

**Comment by aliceriot** [comment] 2016-10-20 15:29
ahh yeah that's right.

**Comment by aliceriot** [comment] 2016-10-21 14:40
@noisecapella I opened a pr to check that out: https://micromasters-ci-pr-1460.herokuapp.com/

I ran into a bunch of issues upgrading material-ui, and given that the issue is still open on their repo I think it's probably safe to say the issue still repros.

Maybe we can talk about how to fix this at retro today

**Comment by pdpinch** [comment] 2016-10-24 16:52
We discussed the possibility of adding an empty value to the list and select it by default.

**Comment by aliceriot** [comment] 2016-11-14 15:28
oop, should have closes this in #1645

**Closed by aliceriot** 2016-11-14 15:28 UTC
Labels: bug
