### ISSUE TITLE
Facet by Degree

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#859] opened 2016-08-16 01:28 UTC

**Comment by pdpinch** [comment] 2016-08-16 01:29
We need to find out what's currently indexed, and we need a design for this in the expanded state.

**Comment by roberthouse54** [comment] 2016-12-21 16:55
So for this one, I am thinking we can either just do checkboxes for each degree type, OR we can do a "Highest degree achieved" thing. But I am leaning toward the first.

**Comment by pdpinch** [comment] 2016-12-21 16:59
Checkboxes make sense to me. That allows the user to construct a search along the lines of "everyone with a bachelors or a masters" 

Can you update with a design?

**Comment by roberthouse54** [comment] 2016-12-21 17:53
The order of the facets should be as follows:
Course
Semester
Avg Grade in Program
# of Completed Courses
Current Residence
Country of Birth
Degree
School
Field of Study
Company
Industry

The first 4 should be open by default. The others should be closed by default.

Degree facet design:

![image](https://cloud.githubusercontent.com/assets/20047260/21400103/7c060646-c77c-11e6-8fab-b7998c6f3927.png)

**Comment by pdpinch** [comment] 2016-12-21 21:14
Normally the sort would be by hits, descending. Can we do that to start?

**Comment by roberthouse54** [comment] 2016-12-21 21:18
Do you want to do that by design? Or because it will be easier to implement?

**Comment by pdpinch** [comment] 2016-12-21 21:19
Primarily, I want to do that because it's easier to implement. 

I think it might also be a good design decision, but I'm not sure. I'm tempted to wait for feedback from users.

**Comment by Ferdi** [comment] 2016-12-21 21:19
I'd go with sorting by hits as well.

**Comment by roberthouse54** [comment] 2016-12-21 21:24
![image](https://cloud.githubusercontent.com/assets/20047260/21406481/e7995bd4-c799-11e6-85e0-ef5df56803eb.png)

**Comment by pdpinch** [comment] 2017-01-03 13:01
@annagav if this is in progress, can you move it to the in progress pipeline?

**Closed** 2017-01-09 17:11 UTC
