### ISSUE TITLE
Figure out UI for work which doesn't have an end date (ie the current job)

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#256] opened 2016-05-03 13:58 UTC
For #150

**Comment by pdpinch** [comment] 2016-05-06 13:52
I think this is addressed by https://invis.io/VC7850ZBS#/156281164_Step_Three_-_Professional_Info_-_Add_Emp_Modal 

??

**Comment by pdpinch** [comment] 2016-05-09 01:48
duplicate of #290

**Closed by pdpinch** 2016-05-09 01:48 UTC
