### ISSUE TITLE
Student dashboard: course start dates and enrollment dates (data only)

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#53] opened 2016-03-10 19:10 UTC
As a student, I need to know when the courses I've enrolled in will start (or when they started in the past) and when future courses will be open for enrollment. 

This will require some research on the appropriate edX API for this data. I believe it is "Course Discovery" 

available in enrollment API:
- [ ] If the user is enrolled, and `start_date` is in the future, we display **starts: [date]**
- [ ] If the user is enrolled, and `start_date` is in the past, we display **started: [date]**

could be done in an asyc task:
- [ ] If the user is not enrolled, and `enrollment_start` is in the future, display **enrollment starts: [date]**
- [ ] If the user is not enrolled and `enrollment_end` is in the past, don't display the course 

also an async task?
- [ ] If the course doesn't exist (yet) display **not yet scheduled** (?)

The "not yet scheduled" courses will require a different model to keep the vague, future data separate from the specific data coming from edX. 

steps:
- [ ] discovery of which edX API to use
- [ ] add edX API to edx_api_client library
- [ ] create REST API in Micromasters that exposes the edx_app_client to the react front-end

**Comment by justinabrahms** [comment] 2016-03-14 17:15
See #3 for some of this information.

Course structure API for the rest.

**Comment by pdpinch** [comment] 2016-03-14 17:24
Add date fields to courses model. Create async task to fetch this data from edX. Use celery beat scheduler.

**Comment by pdpinch** [comment] 2016-03-29 16:33
Instead of pre-fetching this data (using a celery task), let's just fetch the dates when we need them. We can revisit if we find we need to.

**Comment by pdpinch** [comment] 2016-04-06 20:28
I think most of this will be covered by #125.

**Comment by Ferdi** [comment] 2016-04-07 14:23
Closing, duplicate of #125 and #123

**Closed by Ferdi** 2016-04-07 14:23 UTC
