### ISSUE TITLE
Axios upgrade

### ISSUE THREAD

**Issue by Ferdi** [mitodl/micromasters#4516] opened 2020-02-03 22:47 UTC

**Comment by Ferdi** [comment] 2020-02-03 22:49
➤ Peter Pinch commented:

Is this upgrade blocked by Searchkit?

**Comment by Ferdi** [comment] 2020-02-04 18:23
➤ Anna Gavrilman commented:

pdpinch yes, searchkit depends on it

**Comment by Ferdi** [comment] 2020-02-04 19:49
➤ Peter Pinch commented:

I think you've tried this, but I have to ask: can you upgrade Axios underneath searchkit?

**Comment by pdpinch** [comment] 2020-04-20 16:48
duplicate of #4383

**Closed by pdpinch** 2020-04-20 16:48 UTC
