### ISSUE TITLE
Memory warnings on micromasters-rc logs

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1240] opened 2016-10-05 16:05 UTC
I haven't encountered any errors as a user but we should figure out what is causing this and see if it's important

**Comment by pdpinch** [comment] 2016-10-11 15:35
Hoepfully, we can reproduce this with load testing.

**Comment by blarghmatey** [comment] 2016-10-14 16:41
This appears to be due to the fact that the uWSGI server is configured to run 10 processes at launch. I addressed that in #1395 which has been merged. Closing this for now until we see the problem again.

**Closed by blarghmatey** 2016-10-14 16:41 UTC
Labels: DevOps
