### ISSUE TITLE
TypeError: r.refs.cropper is undefined

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2097] opened 2016-12-13 16:07 UTC
Alice, can you take a quick look at this to triage it?

https://sentry.io/mit-office-of-digital-learning/micromasters/issues/193037892/

```
TypeError: r.refs.cropper is undefined
  at originalHandler (./static/js/components/CropperWrapper.js:17:15)
...
(1 additional frame(s) were not displayed)
```

**Comment by aliceriot** [comment] 2016-12-13 16:39
pretty sure this is a dupe of #2096

**Comment by aliceriot** [comment] 2016-12-13 16:40
yeah, one is one FF, this one is Edge. browsers often will spit out different error messages for the same problem. closing.

**Closed by aliceriot** 2016-12-13 16:40 UTC
