### ISSUE TITLE
Home: CSS regression

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4801] opened 2021-02-24 21:36 UTC
In PR #4781 we removed the background color on the Program FAQ page, a regression that had been introduced by the home page update PR #4749.

Unfortunately, when we removed the background color on the FAQ page, we _also_ removed the background color on the home page. I'm embarrassed that we overlooked this. 

### Acceptance criteria

- [ ] Grey background of #EBECED on the homage page, as displayed in [InVision](https://invis.io/YFZ4N7KMWT3#/435513872_Homepage_V2)
- [ ] No background on the program FAQ page (e.g. https://micromasters.mit.edu/scm/frequently-asked-questions/ )

**Comment by umarmughal824** [comment] 2021-02-25 07:03
@pdpinch home page itself has it own dedicated scss files it should not disturb any of the UI but we have changed styling for HubSpot form responsiveness in the faqs page which could be impacted other pages.

But in faq pages, earlier the material-UI grid system was not working properly that I fixed only that could have an impact on the other page but not the home page itself.

**Comment by arslanashraf7** [comment] 2021-02-25 07:36
@umarmughal824 I'm sure this discrepancy was introduced in https://github.com/mitodl/micromasters/pull/4781, Where we attempted to remove background from FAQ tab's content on the program, And due to how it was extended from the homepage we somehow missed the regression of FAQ background on the homepage on part of reusability.
I'm going to put up a PR to fix this.

**Comment by umarmughal824** [comment] 2021-02-25 11:50
> @umarmughal824 I'm sure this discrepancy was introduced in #4781, Where we attempted to remove background from FAQ tab's content on the program, And due to how it was extended from the homepage we somehow missed the regression of FAQ background on the homepage on part of reusability.
> I'm going to put up a PR to fix this.

okay, understood. thanks

**Closed** 2021-03-02 07:36 UTC
