### ISSUE TITLE
Pay now button shown even if user has already paid

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1230] opened 2016-10-04 22:11 UTC
I think I got this bug due to me not being enrolled in edX at the time, but we shouldn't rely on that to show the correct dashboard status since the user can unenroll at any time

**Comment by Ferdi** [comment] 2016-10-05 14:12
This seems tricky to "fix", is that right ?

**Comment by noisecapella** [comment] 2016-10-05 14:26
No it's easy to fix. For financial aid programs, if there is a fulfilled `Order` connected to a course run, we should not show the pay button anymore. I think we currently use the enrollment information from edX to make this determination but for financial aid programs we should just use our `Order` table.

**Comment by pdpinch** [comment] 2016-10-06 16:44
Shoudl this be addressed in the dashboard API, or in the front-end?

**Comment by noisecapella** [comment] 2016-10-06 20:32
It's a dashboard bug, unrelated to #1231 and #1238 which are just about refreshing the dashboard at the right time. I'll look into it now since I'm out of things to do

**Comment by noisecapella** [comment] 2016-10-06 20:33
@giocalitri Does it make sense to remove the requirement for the user to be enrolled on edX before saying that they're verified?

**Comment by giocalitri** [comment] 2016-10-06 21:15
How can this happen? Meaning the user paid but is not enrolled.

**Comment by noisecapella** [comment] 2016-10-06 21:18
There could be a temporary outage on edX when the user pays, or maybe the user unenrolled themselves after paying.

**Comment by giocalitri** [comment] 2016-10-07 01:02
Ok, but if we do like you say, how do we reconcile our DB with the enrollment on edX? Do we try to enroll the user every time she loads the dashboard?

**Comment by noisecapella** [comment] 2016-10-07 14:38
I'm not sure, but it also seems like once they have paid, they should be treated as verified regardless. They may have unenrolled but they didn't get a refund so they should still be treated as verified

**Comment by giocalitri** [comment] 2016-10-07 14:57
I am not sure either, but it seems to me that this state is not a normal one, so we should treat it as an erroneous one. 
Depending on what we will allow the user to do, we might add a specific state for handling this case.

**Comment by Ferdi** [comment] 2016-10-07 15:10
We definitely dont want to ask them pay twice. 

We could if we knew a) they unenrolled on edx AND b) they got a refund from us.  This might be hard to do for this release

I suggest we treat them as unenrolled in all contexts (in search, get the grade etc.) but not allow them allow them to pay.

ok ?

**Comment by pdpinch** [comment] 2016-11-03 13:53
@noisecapella did #1552 address this?

**Comment by noisecapella** [comment] 2016-11-03 14:40
I don't think so. I think the logic says that if the user is not enrolled, the user is shown as not having paid, whether or not they have paid. #1552 only means that the `Order` object is marked as fulfilled, so if the user is enrolled later it will show them as a paid, enrolled user. Here's the relevant function:

    def is_enrolled_mmtrack(self, course_id):
        """
        Returns whether an used is enrolled mmtrack in a course run.
        This means if the user is enrolled verified for normal programs
        or enrolled and paid on micromasters for financial aid ones.

        Args:
            course_id (str): an edX course run id

        Returns:
            bool: whether the user is enrolled mmtrack in the course
        """
        if not self.is_enrolled(course_id):
            return False
        # normal programs need to have a verified enrollment
        if not self.financial_aid_available:
            enrollment = self.enrollments.get_enrollment_for_course(course_id)
            return enrollment.is_verified
        # financial aid programs need to have an audit enrollment and a paid entry for the course
        else:
            return course_id in self.paid_course_ids

**Comment by pdpinch** [comment] 2016-11-28 18:46
The solution to #1568 should address this as well. 

Note that users are already prevented from paying twice, so the issue is how to notify the user of this state and direct them on how to address it.

**Comment by pdpinch** [comment] 2016-12-21 22:25
Now that #1568 is merged, I think we are covered.

**Closed by pdpinch** 2016-12-21 22:25 UTC
Labels: bug
